# arxivの学問領域の指定
subject: 'cat:q-bio.BM OR cat:q-bio.CB OR cat:q-bio.GN OR cat:q-bio.MN'

# 検索キーワード
keywords:
        flippase: 2
        ciliary: 3
        dynein: 1
        retrograde: 1
        ezrin: 1
        phosrhatidylserine: 1
        plasma membrane: 2

# 通知の閾値
score_threshold: 3
